# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "whoiszzj"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 10

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# keywords to search
keywords:
    "NeRF":
        filters: ["nerf", "neural rendering", "implicit field", "radiance field", "volumetric rendering", "neus", "sdf"]
    "GaussianSplatting":
        filters: ["gaussian splatting", "3d gaussians"]
    "MVS":
        filters: ["mvs", "multi-view", "multiview", "stereo"]
    "SFM":
        filters: ["sfm", "Structure from Motion"]
